### ISSUE TITLE
建议把下面的课程推荐广告也去了吧

### ISSUE THREAD

**Issue by CHN-STUDENT** [Programming-With-Love/CSDNGreener#9]
![image](https://user-images.githubusercontent.com/21209416/67631572-3efbfb80-f8d3-11e9-96ef-aad0a3e7c338.png)
RT，还技术一片故土，这广告看着也没意思。
感谢您！
测试文章：https://blog.csdn.net/xiaocszn/article/details/81709061
再次感激您！

**Comment by AdlerED** [comment]
感谢你的反馈呦~已经搞定了，请点击右上角油猴图标-用户脚本检查更新，让油猴将脚本自动更新到最新版本即可，欢迎下次继续提供反馈！:smile:

**Comment by AdlerED** [comment]
#a4c4b96
